server:
  port: 8080
  servlet: #小程序或者称之为服务连接器
    context-path: /myweb #上下文路径

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jtadmin?characterEncoding=utf8
    username: root
    password: root

mybatis:
  type-aliases-package: com.myweb.pojo
  mapper-location: classpath:/mybatis/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
