server:
  port: 8090   #定义端口号
  servlet:
    context-path:

spring:
  thymeleaf:
    #    设置前缀
    prfix: classpath:/templates/
    #    设置后缀
    suffix: .html
    #    是否使用缓存
    cache: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jtadmin?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root

mybatis-plus:
  #定义别名包
  type-aliases-package: com.jt.pojo
  mapper-locations: classpath:/mybatis/mappers/*.xml
  #开启驼峰映射
  configuration:
    map-underscore-to-camel-case: true
#添加MP 日志 打印执行sql
logging:
  level:
    com.jt.mapper: debug