server:
  port: 8080
  servlet:
    context-path: /myweb


spring:
  datasource:
    url: jdbc:mysql:///jtadmin
    username: root
    password: root

#SpringBoot整合MyBatis配置
mybatis-plus:
  #定义别名包
  type-aliases-package: com.myweb.pojo
  mapper-locations: classpath:/mybatis/mappers/*.xml
  #开启驼峰映射
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.myweb.mapper: debug
